label: Pagination
status: wip
order: -1

context:
  placeholder_link: "javascript:void(0);"
  modifier: ''
  aria_label: 'pagination'
  pagination:
    items: 24
    current: 10


variants:
  - name: Centered
    context:
      modifier: usa-pagination--centered
