label: Pagination
preview: "@uswds-framed"

context:
  lang: en
  placeholder_link: javascript:void(0);
  modifier: ''
  aria_label: Pagination
  pagination:
    page_label: Page
    infinite: false
    items: 24
    current: 10
    previous:
      label: Previous
    next:
      label: Next
    last_item:
      label: Last page,

variants:
  - name: infinite
    label: Infinite
    context:
      modifier: usa-pagination--infinite
      aria_label: Pagination,
      pagination:
        items: 24
        current: 10
        infinite: true
  - name: lang-es
    label: Spanish
    context:
      lang: en
      aria_label: Paginación
      pagination:
        page_label: Página
        previous:
          label: Anterior
        next:
          label: Siguiente
        last_item:
          label: Última página,
  - name: infinite-lang-es
    label: Infinite (Spanish)
    context:
      lang: es
      modifier: usa-pagination--infinite
      aria_label: Paginación,
      pagination:
        page_label: Página
        infinite: true
        previous:
          label: Anterior
        next:
          label: Siguiente
        last_item:
          label: Última página,
