label: Site Alert
context:
  siteAlert:
    close_svg: /img/close.svg
    dismissible: true
  alert:
    content: 'Lorem ipsum dolor sit amet, <a href="javascript:void(0);">consectetur adipiscing</a> elit, sed do eiusmod.'

variants:
  - name: info
    label: Info
    context:
      siteAlert:
        classes: "usa-site-alert--info"
      alert:
        title: Informative status

  - name: warning
    label: Warning
    context:
      siteAlert:
        classes: "usa-site-alert--warning"
      alert:
        title: Warning status

  - name: warning-grid-contained
    label: Warning Grid Contained
    context:
      siteAlert:
        classes: "usa-site-alert--warning usa-site-alert--grid-contained"
      alert:
        title: Warning status

  - name: error
    label: Error
    context:
      siteAlert:
        classes: "usa-site-alert--error"
      alert:
        title: Error status
        role: "alert"

  - name: emergency
    label: Emergency
    context:
      siteAlert:
        close_svg: /img/close-white.svg
        classes: "usa-site-alert--emergency"
      alert:
        title: Emergency status
        role: "alert"

  - name: emergency-grid-contained-list
    label: Emergency Grid Contained with List
    context:
      siteAlert:
        close_svg: /img/close-white.svg
        classes: "usa-site-alert--emergency usa-site-alert--grid-contained"
      alert:
        title: Emergency status
        content: false
        list: '
          <ul class="usa-list">
          <li>Lorem ipsum dolor sit amet, <a href="javascript:void(0);">consectetur adipiscing</a> elit, sed do eiusmod.</li>
          <li>Lorem ipsum dolor sit amet, <a href="javascript:void(0);">consectetur adipiscing</a> elit, sed do eiusmod.</li>
          <li>Lorem ipsum dolor sit amet, <a href="javascript:void(0);">consectetur adipiscing</a> elit, sed do eiusmod.</li>
          </ul>'

  - name: no-header
    label: No header
    context:
      siteAlert:
        classes: "usa-site-alert--info"
        dismissible: false
      alert:
        content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod."

  - name: no-icon
    label: No icon
    context:
      siteAlert:
        classes: "usa-site-alert--info"
      alert:
        classes: "usa-alert--no-icon"
        content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod."

  - name: slim
    label: Slim
    context:
      siteAlert:
        classes: "usa-site-alert--info"
      alert:
        classes: "usa-alert--slim"
        content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod."
