label: Step indicator
status: ready
preview: "@uswds-content"
context:
  showLabels: true
  currentStep: 3
  steps:
    - step:
      status: complete
      label: Personal information
    - step:
      status: complete
      label: Household status
    - step:
      status: current
      label: Supporting documents
    - step:
      status: incomplete
      label: Signature
    - step:
      status: incomplete
      label: Review and submit

variants:
  - name: default
    context:
      heading: Default

  - name: short
    context:
      heading: Only a few steps
      showLabels: true
      currentStep: 2
      steps:
        - step:
          status: complete
          label: Personal information
        - step:
          status: current
          label: Household status
        - step:
          status: incomplete
          label: Supporting documents

  - name: centered
    context:
      heading: centered
      showLabels: true
      centered: true
      variants:
        - center

  - name: counters
    context:
      heading: Add counters
      showLabels: true
      variants:
        - counters

  - name: counters-sm
    context:
      heading: Add small counters
      showLabels: true
      variants:
        - counters-sm

  - name: centered-counters
    context:
      heading: Centered and counters
      showLabels: true
      variants:
        - counters
        - center

  - name: centered-counters-sm
    context:
      heading: Centered and counters
      showLabels: true
      variants:
        - counters-sm
        - center

  - name: no-labels
    context:
      heading: No labels
      showLabels: false
      variants:
        - no-labels

  - name: centered-no-labels
    context:
      heading: Centered and no labels
      variants:
        - no-labels
        - center

  - name: counters-no-labels
    context:
      heading: Counters and no labels
      variants:
        - no-labels
        - counters

  - name: small-counters-no-labels
    context:
      heading: Small counters and no labels
      variants:
        - no-labels
        - counters-sm

  - name: centered-counters-no-labels
    context:
      heading: Centered counters and no labels
      variants:
        - no-labels
        - counters
        - center

  - name: centered-counters-sm-no-labels
    context:
      heading: Centered small counters and no labels
      variants:
        - no-labels
        - counters-sm
        - center
