label: Step indicator
status: ready
preview: "@uswds-content"
context:
  showLabels: true
  currentStep: 3
  steps:
    - step:
      status: complete
      label: Personal information
    - step:
      status: complete
      label: Household status
    - step:
      status: current
      label: Documents
    - step:
      status: incomplete
      label: Work history
    - step:
      status: incomplete
      label: Signature
    - step:
      status: incomplete
      label: Review and submit

variants:
  - name: default
    context:
      heading: Default


  - name: short
    context:
      heading: Only a few steps
      showLabels: true
      currentStep: 2
      steps:
        - step:
          status: complete
          label: Personal information
        - step:
          status: current
          label: Household status
        - step:
          status: incomplete
          label: Documents

  - name: centered
    context:
      heading: centered
      showLabels: true
      centered: true

  - name: No counter
    context:
      heading: No numbered counters
      showLabels: true
      variant: no-counter

  - name: centered-no-counter
    context:
      heading: Centered and no counter
      showLabels: true
      centered: true
      variant: no-counter


  - name: No labels
    context:
      heading: No labels
      showLabels: false
      variant: no-labels

  - name: centered-no-labels
    context:
      heading: Centered and no labels
      centered: true
      variant: no-labels

