version: "2"
plugins:
  duplication:
    enabled: true
    config:
      languages:
        - javascript
exclude_patterns:
  - config/**/*.js
  - dist/**/*.js
  - src/patterns/**/**/*.js"
  - src/js/vendor/**/*.js
