version: "2"
plugins:
  duplication:
    enabled: true
    config:
      languages:
        - javascript
exclude_patterns:
  - config/**/*.js
  - dist/**/*.js
  - spec/**/*
  - src/patterns/js/vendor/**/*.js
