version: "2"
plugins:
  duplications:
    enabled: true
    config:
      languages:
        - javascript
exclude_patterns:
  - config/**/*.js
  - dist/**/*.js
  - spec/**/*
  - src/js/vendor/**/*.js
