parser: "@babel/eslint-parser"
parserOptions:
  requireConfigFile: false
  babelOptions:
    plugins:
      - '@babel/plugin-syntax-import-assertions'
extends:
  - airbnb-base
  - prettier
plugins:
  - import
  - no-unsanitized
env:
  node: true
  browser: true
  es2021: true
  mocha: true
rules:
  import/no-extraneous-dependencies:
    - error
    - devDependencies: true
  no-unsanitized/method: error
  no-unsanitized/property: error
overrides:
  - { files: ['*.spec.js'],
      rules: {
        no-unsanitized/method: off,
        no-unsanitized/property: off
        }
      }
