# Markdown config
markdown: redcarpet
highlighter: rouge
name: Draft U.S. Web Design Standards
exclude:
- go
- Gemfile
- Gemfile.lock
- README.md
- LICENSE.md
- CONTRIBUTING.md
- ".sass-cache"
- ".ruby-version"
- vendor

permalink: pretty

google_analytics_ua: UA-48605964-33

sass:
  sass_dir: assets/_scss
#  style: :compressed

collections:
  visual:
    output: true
    permalink: /:path/
  layout-system:
    output: true
    permalink: /:path/
  elements:
    output: true
    permalink: /:path/
  components:
    output: true
    permalink: /:path/
