# Markdown config
markdown: redcarpet
highlighter: pygments
name: U.S. Open Data Shared Services
exclude:
- go
- Gemfile
- Gemfile.lock
- README.md
- LICENSE.md
- CONTRIBUTING.md
- ".sass-cache"
- ".ruby-version"
- vendor

permalink: pretty
baseurl: /web-design-standards

repos:
- name: U.S. Web Design Standards
  description: Main repository for the U.S. Web Design Standards.
  url: https://github.com/18F/web-design-standards
- name: U.S. Open Data Shared Services
  description: Shared Services to help government agencies automate registering Open Data to Data.gov
  url: https://github.com/18F/web-design-standards-assets

google_analytics_ua: UA-48605964-33

sass:
  sass_dir: assets/_scss
#  style: :compressed

collections:
  visual:
    output: true
    permalink: /:path/
  layout-system:
    output: true
    permalink: /:path/
  elements:
    output: true
    permalink: /:path/
  components:
    output: true
    permalink: /:path/
  datasets:
    output: true
    permalink: /:path/
