# 18F pages base url config
baseurl: /usfwds

url: https://pages.18f.gov/usfwds

# Markdown config
markdown: redcarpet
highlighter: rouge
name: U.S. Federal Web Design Standards
exclude:
- go
- Gemfile
- Gemfile.lock
- README.md
- LICENSE.md
- CONTRIBUTING.md
- ".sass-cache"
- ".ruby-version"
- vendor

permalink: pretty

repos:
- name: U.S. Federal Web Design Standards
  description: Main repository for the U.S. Federal Web Design Standards.
  url: https://github.com/18F/usfwds

google_analytics_ua: UA-48605964-19

sass:
  sass_dir: assets/_scss
#  style: :compressed

collections:
  visual:
    output: true
    permalink: /visual-style/:path/
  layout-system:
    output: true
    permalink: /layout-system/:path/
  elements:
    output: true
    permalink: /elements/:path/
  components:
    output: true
    permalink: /components/:path/
