label: Banner Violator
status: ready
context:
  banner:
    dismissible: true
  alert:
    content: 'Lorem ipsum dolor sit amet, <a href="javascript:void(0);">consectetur adipiscing</a> elit, sed do eiusmod.'

variants:
  - name: info
    label: Info
    context:
      banner:
        classes: "usa-alert-banner--info"
      alert:
        classes: ""
        title: Informative status

  - name: success
    label: Success
    context:
      banner:
        classes: "usa-alert-banner--success"
      alert:
        classes: ""
        title: Success status

  - name: warning
    label: Warning
    context:
      banner:
        classes: "usa-alert-banner--warning"
      alert:
        classes: ""
        title: Warning status

  - name: warning-grid-contained
    label: Warning Grid Contained
    context:
      banner:
        classes: "usa-alert-banner--warning usa-alert-banner--grid-contained"
      alert:
        classes: ""
        title: Warning status

  - name: error
    label: Error
    context:
      banner:
        classes: "usa-alert-banner--error"
      alert:
        classes: ""
        title: Error status
        role: "alert"

  - name: emergency
    label: Emergency
    context:
      banner:
        classes: "usa-alert-banner--emergency"
      alert:
        classes: ""
        title: Emergency status
        role: "alert"

  - name: emergency-grid-contained-list
    label: Emergency Grid Contained with List
    context:
      banner:
        classes: "usa-alert-banner--emergency usa-alert-banner--grid-contained"
      alert:
        classes: ""
        title: Coronavirus Information 
        content: false
        list: '
          <ul class="usa-list">
            <li><a href="https://www.cdc.gov/coronavirus/2019-ncov/prevent-getting-sick/prevention.html" target="_blank">How to prepare and protect yourself</a></li>
            <li><a href="https://www.cdc.gov/coronavirus/2019-ncov/if-you-are-sick/index.html" target="_blank">What to do if you think you are sick</a></li>
            <li><a href="https://www.hhs.gov/coronavirus/community-based-testing-sites/index.html" target="_blank">Find a Testing Location</a></li>
          </ul>'

  - name: no-header
    label: No header
    context:
      banner:
        classes: "usa-alert-banner--info"
      alert:
        classes: ""
        content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod."


  - name: no-icon
    label: No icon
    context:
      banner:
        classes: "usa-alert-banner--info"
      alert:
        classes: "usa-alert--no-icon"
        content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod."

  - name: slim
    label: Slim
    context:
      banner:
        classes: "usa-alert-banner--info"
      alert:
        classes: "usa-alert--slim"
        content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod."
