label: Primary (header)
preview: '@uswds-header'

context:
  nav:
    search: false
    links:
      - text: Current section dropdown
        is_current: true
        id: nav-section-one
        links: &subnav_links
          - text: Navigation link
            href: '#'
          - text: Navigation link
            href: '#'
          - text: Navigation link
            href: '#'
          - text: Navigation link
            href: '#'
          - text: A very long navigation link that goes onto two lines
            href: '#'
          - text: Navigation link
            href: '#'
          - text: Navigation link
            href: '#'
          - text: Navigation link
            href: '#'
          - text: Navigation link
            href: '#'
      - text: Section dropdown
        id: nav-section-two
        links: *subnav_links
      - text: Navigation link
        href: 'javascript:void(0)'
