version: 2.1

orbs:
  snyk: snyk/snyk@0.0.12
  browser-tools: circleci/browser-tools@1.0.1

references:
  container: &container
    docker:
      - image: misterio92/ci-php-node
        environment:
          CHROME_PATH: /usr/local/bin/google-chrome

  restore_deps: &restore_deps
    restore_cache:
      keys:
        - v2-uswds-dependencies-{{ checksum "package-lock.json" }}

jobs:
  build:
    <<: *container
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-uswds-dependencies-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v2-uswds-dependencies-{{ checksum "package-lock.json" }}
      - snyk/scan:
          organization: uswds
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          name: Build Patternlab
          command: npm run build
      - run:
          name: Run test
          command: npm run test:ci:temp

  deploy:
    <<: *container
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-uswds-dependencies-{{ checksum "package-lock.json" }}
      - run: npm install --ignore-scripts
      - run: npm rebuild node-sass
      - run:
          name: Build the USWDS package
          command: npm run build
      - run:
          name: Publish to NPM
          command: |
            npm config set "//registry.npmjs.org/:_authToken=$NPM_TOKEN"
            npm publish

  deploy-alpha:
    <<: *container
    steps:
      - checkout
      - run: npm install --ignore-scripts
      - run: npm rebuild node-sass
      - run:
          name: Build the USWDS package
          command: npm run build
      - run:
          name: Publish to NPM with `alpha` tag
          command: |
            npm config set "//registry.npmjs.org/:_authToken=$NPM_TOKEN"
            npm publish --tag alpha

  deploy-beta:
    <<: *container
    steps:
      - checkout
      - run: npm install --ignore-scripts
      - run: npm rebuild node-sass
      - run:
          name: Build the USWDS package
          command: npm run build
      - run:
          name: Publish to NPM with `beta` tag
          command: |
            npm config set "//registry.npmjs.org/:_authToken=$NPM_TOKEN"
            npm publish --tag beta

workflows:
  version: 2
  circle-uswds:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
      - deploy-beta:
          requires:
            - build
          filters:
            branches:
              only: v2.10-beta--main
