version: 2

references:
  container: &container
    docker:
      - image: circleci/node:8.10-browsers
  
  restore_deps: &restore_deps
    restore_cache:
      keys:
        - v1-uswds-dependencies-{{ checksum "package-lock.json" }}
        - v1-uswds-dependencies-

jobs:
  build:
    <<: *container
    steps:
      - checkout
      - run:
          name: Install codeclimate
          command: sudo npm install -g codeclimate-test-reporter
      - *restore_deps
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-uswds-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Run test
          command: npm test
      - run:
          name: Run code coverage report
          command: npm run cover
      - run:
          name: Checking build
          command: |
            ls -agolf dist/
            codeclimate-test-reporter < coverage/lcov.info

  deploy:
    <<: *container
    steps:
      - checkout
      - *restore_deps
      - run: npm install --ignore-scripts
      - run:
          name: Build the USWDS package
          command: npm run release
      - run:
          name: Publish to NPM
          command: |
            npm config set "//registry.npmjs.org/:_authToken=$NPM_TOKEN"
            npm publish
  
  prerelease:
    <<: *container
    steps:
      - checkout
      - *restore_deps
      - run: npm install --ignore-scripts
      - run:
          name: Build the USWDS package
          command: npm run release
      - run:
          name: Publish to NPM
          command: |
            npm config set "//registry.npmjs.org/:_authToken=$NPM_TOKEN"
            npm publish . --tag alpha

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
      - prerelease:
          requires:
            - build
          filters:
            branches:
              only: /^.+-alpha(\.[0-9]{1})?/
