label: Identifier
status: wip
context:
  taxpayer: false
  usagov: true
  domain: domain.gov
  parent:
    name: <Parent agency>
    shortname: <Parent shortname>
    url: javascript:void(0);
    logo: default
  links:
    about: javascript:void(0);
    accessibility: javascript:void(0);
    foia: javascript:void(0);
    no_fear: javascript:void(0);
    oig: javascript:void(0);
    performance: javascript:void(0);
    privacy: javascript:void(0);

variants:
  - name: no logos
    label: No Logos
    context:
      parent:
        logo: false

  - name: multiple logos
    label: Multiple Logos
    context:
      agency:
        name: <Other agency>
        shortname: false
        url: https://gsa.gov/
        logo: default
