label: Identifier
status: ready
context:
  lang: en
  domain: domain.gov
  masthead:
    label:
      content:
        en: Agency identifier_
        es: Identificador de la agencia_
    description:
      label:
        content:
          en: Agency description
          es: Descripción de la agencia
    text:
      content:
        en: An official website of the
        es: Un sitio web oficial de
    parent:
      name:
        en: <Parent agency>
        es: <Parent agency>
      shortname: <Parent shortname>
      url:
        en: javascript:void(0);
        es: javascript:void(0);
      logo: default
    agency:
      name:
        en:
        es:
      shortname:
      url:
        en:
        es:
      logo:
    taxpayer_disclaimer:
      content:
        en: Produced and published at taxpayer expense.
        es: Producido y publicado con dinero de los contribuyentes de impuestos.
      display: false
  required_links:
    label:
      content:
        en: Important links_
        es: Enlaces importantes_
    links:
      about:
        content:
          en: About
          es: Acerca de
        url:
          en: javascript:void(0);
          es: javascript:void(0);
      accessibility:
        content:
          en: Accessibility support
          es: Soporte de accesibilidad
        url:
          en: javascript:void(0);
          es: javascript:void(0);
      foia:
        content:
          en: FOIA requests
          es: Solicitud a través de FOIA
        url:
          en: javascript:void(0);
          es: javascript:void(0);
      no_fear:
        content:
          en: No FEAR Act data
          es: Datos de la ley No FEAR
        url:
          en: javascript:void(0);
          es: javascript:void(0);
      oig:
        content:
          en: Office of the Inspector General
          es: Oficina del Inspector General
        url:
          en: javascript:void(0);
          es: javascript:void(0);
      performance:
        content:
          en: Performance reports
          es: Informes de desempeño
        url:
          en: javascript:void(0);
          es: javascript:void(0);
      privacy:
        content:
          en: Privacy policy
          es: Política de privacidad
        url:
          en: javascript:void(0);
          es: javascript:void(0);
  usagov:
    label:
      content:
        en: U.S. government information and services_
        es: Información y servicios del Gobierno de EE. UU._
    description:
      content:
        en: Looking for U.S. government information and services?
        es: ¿Necesita información y servicios del Gobierno?
    link:
      content:
        en: Visit USA.gov
        es: Visite USAGov en Español
      url:
        en: https://www.usa.gov/
        es: https://www.usa.gov/espanol/
    display: true

variants:
  - name: lang-es
    label: Spanish
    context:
      lang: es
  - name: no-logos
    label: No Logos
    context:
      masthead:
        label:
          content:
            en: Agency identifier__
        parent:
          logo: false
      usagov:
        label:
          content:
            en: U.S. government information and services__
      required_links:
        label:
          content:
            en: Important links__
  - name: no-logos-lang-es
    label: No Logos (Spanish)
    context:
      lang: es
      masthead:
       label:
        content:
          es: Identificador de la agencia__
       parent:
          logo: false
      usagov:
        label:
          content:
            es: Información y servicios del Gobierno de EE. UU.__
      required_links:
        label:
          content:
            es: Enlaces importantes__
  - name: multiple-logos
    label: Multiple Logos
    context:
      masthead:
        label:
          content:
            en: Agency identifier___
        agency:
          name:
            en: <Other agency>
          shortname: false
          url:
            en: javascript:void(0);
          logo: default
      usagov:
        label:
          content:
            en: U.S. government information and services___
      required_links:
        label:
          content:
            en: Important links___
  - name: multiple-logos-lang-es
    label: Multiple Logos (Spanish)
    context:
      lang: es
      masthead:
       label:
        content:
          es: Identificador de la agencia___
        agency:
          name:
            es: <Other agency>
          shortname: false
          url:
            es: javascript:void(0);
          logo: default
      usagov:
        label:
          content:
            es: Información y servicios del Gobierno de EE. UU.___
      required_links:
        label:
          content:
            es: Enlaces importantes___
  - name: taxpayer-disclaimer
    label: Taxpayer disclaimer
    context:
      masthead:
        label:
          content:
            en: Agency identifier____
        taxpayer_disclaimer:
          display: true
      usagov:
        label:
          content:
            en: U.S. government information and services____
      required_links:
        label:
          content:
            en: Important links____
  - name: taxpayer-disclaimer-lang-es
    label: Taxpayer disclaimer (Spanish)
    context:
      lang: es
      masthead:
       label:
        content:
          es: Identificador de la agencia____
        taxpayer_disclaimer:
          display: true
      usagov:
        label:
          content:
            es: Información y servicios del Gobierno de EE. UU.____
      required_links:
        label:
          content:
            es: Enlaces importantes____
