label: Breadcrumb
status: ready
preview: "@uswds-content"
context:
  variantARIA: Breadcrumbs,,
  variantClass: usa-breadcrumb--wrap

variants:
  - name: wrap
    context:
      variantARIA: Breadcrumbs,,,
      variantClass: usa-breadcrumb--wrap
