label: Breadcrumb
status: ready
preview: "@uswds-content"
context:
  variantARIA: Default breadcrumb
  variantClass: usa-breadcrumb--wrap

variants:
  - name: wrap
    context:
      variantARIA: Wrapping breadcumb
      variantClass: usa-breadcrumb--wrap
