label: Secondary (header)
preview: "@uswds-header"
status: ready

context:
  nav:
    search: true
    links:
      - text: Secondary link
      - text: Another secondary link

variants:
  - name: lang-es
    context:
      nav:
        links:
          - text: Enlace secundario
          - text: Otro enlace secundario
