label: Card
preview: "@uswds-content"

context:
  card:
    title: "What is a card?"
    content:
      - Lorem ipsum dolor sit amet consectetur adipisicing elit.
        Facilis earum tenetur quo cupiditate, eaque qui officia recusandae.
        Facere magnam quo nostrum amet odio ut ducimus?

variants:
  - name: compare
    label: Compare
    context:
      cards:
        - name: default
          title: Card
          content:
            - Lorem ipsum dolor sit amet consectetur adipisicing elit.
              Facilis earum tenetur quo cupiditate, eaque qui officia recusandae.
              Excepturi nobis dolores molestias! Quas quisquam a officia eos.
        - name: raised
          title: Card with media
          media: true
          content:
            - Lorem ipsum dolor sit amet consectetur adipisicing elit.
              Facilis earum tenetur quo cupiditate, eaque qui officia recusandae.
              Excepturi nobis dolores molestias! Quas quisquam a officia eos.
        - name: media
          title: Media and header first
          classes: "usa-card--header-first"
          media: true
          content:
            - Lorem ipsum dolor sit amet consectetur adipisicing elit.
              Facilis earum tenetur quo cupiditate, eaque qui officia recusandae.
        - name: media_inset
          title: Inset media
          classes: "usa-card--header-first"
          media: true
          media_classes: "usa-card__media--inset"
          content:
            - Lorem ipsum dolor sit amet consectetur adipisicing elit.
              Facilis earum tenetur quo cupiditate, eaque qui officia recusandae.
        - name: media_exdent
          title: Exdent media
          classes: "usa-card--header-first"
          media: true
          media_classes: "usa-card__media--exdent"
          content:
            - Lorem ipsum dolor sit amet consectetur adipisicing elit.
              Facilis earum tenetur quo cupiditate, eaque qui officia recusandae.
        - name: flag
          classes: "usa-card--flag"
          title: Flag default
          media: true
          media_classes: "flex-align-center"
          image_classes: "circle-card margin-x-auto usa-card__media--inset"
          flag: true
          content:
            - Lorem ipsum dolor sit amet consectetur adipisicing elit.
        - name: flag-right
          classes: "usa-card--flag usa-card--media-right"
          title: Flag media on right
          media: true
          flag: true
          content:
            - Lorem ipsum dolor sit amet consectetur adipisicing elit.

  - name: default

  - name: media
    label: Media
    context:
      card:
        classes: "usa-card--media"
        title: Florida Keys
        id: "card-media"
        media: true
