label: Card
status: prototype
order: 1
preview: "@uswds-content"
collated: false

context:
  card:
    title:  "What is a card?"
    content:
      - A card is typically a member of a collection a subset or summary of a parent/record.
        It includes at least an actionable element. It's modular and distinct from its collection peers in content.
    actions:
      button: true
      link: false
      social: false

variants:
  - name: default
    label: Default
    context:
      card:
        classes: "usa-card"
        title: What is a card?
        id: "whats-a-card"

  - name: raised
    label: Raised
    context:
      card:
        classes: "usa-card--raised"
        title: Make your card standout
        id: "card-standout"

  - name: media
    label: Media Card
    context:
      card:
        media: true
        classes: "usa-card--media"
        title: Media Card
