label: Card
preview: "@uswds-content"

context:
  card:
    title: "What is a card?"
    content:
      - Lorem ipsum dolor sit amet consectetur adipisicing elit.
        Facilis earum tenetur quo cupiditate, eaque qui officia recusandae.
        Facere magnam quo nostrum amet odio ut ducimus?

variants:
  - name: compare
    label: Compare
    context:
      cards:
        - name: default
          classes: ""
          title: Card
          content:
            - Lorem ipsum dolor sit amet consectetur adipisicing elit.
              Facilis earum tenetur quo cupiditate, eaque qui officia recusandae.
              Excepturi nobis dolores molestias! Quas quisquam a officia eos.
        - name: raised
          classes: "usa-card--raised"
          title: Raised card
          content:
            - Lorem ipsum dolor sit amet consectetur adipisicing elit.
              Facilis earum tenetur quo cupiditate, eaque qui officia recusandae.
              Excepturi nobis dolores molestias! Quas quisquam a officia eos.
        - name: media
          classes: "usa-card--media"
          title: Media card
          media: true
          content:
            - Lorem ipsum dolor sit amet consectetur adipisicing elit.
              Facilis earum tenetur quo cupiditate, eaque qui officia recusandae.
        - name: flag
          classes: "usa-card--flag"
          title: Flag default
          media: true
          flag: true
          content:
            - Lorem ipsum dolor sit amet consectetur adipisicing elit.
              Facilis earum tenetur quo cupiditate, eaque qui officia recusandae.
        - name: flag-right
          classes: "usa-card--flag usa-card--media-right"
          title: Flag media on right
          media: true
          flag: true
          content:
            - Lorem ipsum dolor sit amet consectetur adipisicing elit.
              Facilis earum tenetur quo cupiditate, eaque qui officia recusandae.

  - name: default

  - name: media
    label: Media
    context:
      card:
        classes: "usa-card--media"
        title: Florida Keys
        id: "card-media"
        media: true

  - name: raised
    label: Raised
    context:
      card:
        classes: "usa-card--raised"
        title: Florida Keys
        id: "card-standout"

  - name: equal-height
    label: Equal Height
    context:
      card:
        classes: "usa-card--equal-height"
        title: Florida Keys
        id: "card-equal-height"
