label: Card
status: draft
order: 1
preview: "@uswds-content"

context:
  card:
    title: "What is a card?"
    content:
      - A card is typically a member of a collection of similar cards as well as a subset or summary of a parent record.
        It includes at least an actionable element. It's modular and distinct from its collection peers in content.

variants:
  - name: compare
    label: Compare
    context:
      cards:
        - name: default
          classes: ""
          title: Default card
          content:
            - A card is typically a member of a collection of similar cards as well as a subset or summary of a parent record.
        - name: raised
          classes: "usa-card--raised"
          title: Raised Card
          content:
            - A raised card is a way to make a card stand out from its context.
        - name: media
          classes: "usa-card--media"
          title: Media card
          media: true
          content:
            - Adding media to a card can help visually distinguish it from
              its peers.
        - name: flag
          classes: "usa-card--flag"
          title: Flag default
          media: true
          flag: true
          content:
            - Some filler text.
        - name: flag-right
          classes: "usa-card--flag usa-card--media-right"
          title: Flag media on right
          media: true
          flag: true
          content:
            - Some filler text.

  - name: default

  - name: media
    label: Media
    context:
      card:
        classes: "usa-card--media"
        title: Showoff photography
        id: "card-media"
        media: true

  - name: raised
    label: Raised
    context:
      card:
        classes: "usa-card--raised"
        title: Make your card stand out from its context
        id: "card-standout"

  - name: equal-height
    label: Equal Height
    context:
      card:
        classes: "usa-card--equal-height"
        title: Equal height as a class or mixin
        id: "card-equal-height"
