label: File input
status: ready
collated: true

variants:
  - name: default
    context:
      id: single
      label: Input a single file

  - name: specific
    context:
      id: specific
      label: Input only specific file types
      hint: Attach PDF or TXT files
      accept:
        - .pdf
        - .txt

  - name: multiple
    context:
      label: Input multiple files
      id: multiple
      hint: Attach one or more files
      multiple: true

  - name: error
    context:
      id: error
      label: Input with an error
      hint: Attach any valid file
      error: true
      errorMessage: Display a helpful error message

  - name: disabled
    context:
      id: disabled
      label: Disabled input
      disabled: true
