label: Icon list
status: wip
preview: "@uswds-content"
context:
  items:
    - icon:
        name: check_circle
        size: lg
        color: green
      content: Donate cash when possible.
    - icon:
        name: check_circle
        size: lg
        color: green
      content: Confirm what donations are needed.
    - icon:
        name: cancel
        color: secondary
      content: Don't just show up to a disaster area.

variants:
  - name: rich
    label: Rich content
    context:
      items:
        - icon:
            name: check_circle
            color: ink
            utilities:
          content: |
            <h3 class="margin-0 line-height-sans-3">Donate cash when possible.</h2>
            <p class="margin-top-1">Financial contributions to recognized disaster relief organizations are the fastest, most flexible and most effective method of donating. Organizations on the ground know what items and quantities are needed, often buy in bulk with discounts and, if possible, purchase through businesses local to the disaster, which supports economic recovery.</p>

        - icon:
            name: check_circle
            color: ink
            utilities:
          content: |
            <h3 class="margin-0 line-height-sans-3">Confirm what donations are needed.</h3>
            <p class="margin-top-1">Unneeded and unsolicited goods burden local organizations’ ability to meet survivors’ confirmed needs, drawing away valuable volunteer labor, transportation and warehouse space.</p>

        - icon:
            name: check_circle
            color: ink
            utilities:
          content: |
            <h3 class="margin-0 line-height-sans-3">Talk to trusted organizations about volunteering.</h3>
            <p class="margin-top-1">Financial contributions to recognized disaster relief organizations are the fastest, most flexible and most effective method of donating. Organizations on the ground know what items and quantities are needed, often buy in bulk with discounts and, if possible, purchase through businesses local to the disaster, which supports economic recovery.</p>
  - name: large-icon
    label: Custom size
    context:
      iconSize: lg
      items:
        - icon:
            name: check_circle
            color: ink
            utilities:
          content: Donate cash when possible.
        - icon:
            name: check_circle
            color: ink
            utilities:
          content: Confirm what donations are needed.
        - icon:
            name: check_circle
            color: ink
            utilities:
          content: Talk to trusted organizations about volunteering.
  - name: rich-large
    label: Custom size with rich content
    context:
      iconSize: lg
      items:
        - icon:
            name: check_circle
            color: ink
            utilities:
          content: |
            <h3 class="margin-0">Donate cash when possible.</h2>
            <p class="margin-top-1">Financial contributions to recognized disaster relief organizations are the fastest, most flexible and most effective method of donating. Organizations on the ground know what items and quantities are needed, often buy in bulk with discounts and, if possible, purchase through businesses local to the disaster, which supports economic recovery.</p>

        - icon:
            name: check_circle
            color: ink
            utilities:
          content: |
            <h3 class="margin-0">Confirm what donations are needed.</h3>
            <p class="margin-top-1">Unsolicited goods NOT needed burden local organizations’ ability to meet survivors’ confirmed needs, drawing away valuable volunteer labor, transportation and warehouse space.</p>

        - icon:
            name: check_circle
            color: ink
            utilities:
          content: |
            <h3 class="margin-0">Talk to trusted organizations about volunteering.</h3>
            <p class="margin-top-1">Financial contributions to recognized disaster relief organizations are the fastest, most flexible and most effective method of donating. Organizations on the ground know what items and quantities are needed, often buy in bulk with discounts and, if possible, purchase through businesses local to the disaster, which supports economic recovery.</p>
