label: Summary box
status: wip
preview: "@uswds-content"
context:
  summaryBox:
    content: 
      - '<ul>
          <li>If you are under a winter storm warning, find shelter right away.</li>
          <li>Sign up for your community’s warning system.</li>
          <li>Learn the signs of, and basic treatments for, frostbite and hypothermia.</li>
          <li>Gather emergency supplies for your home and your car.</li>
        </ul>'
    title: Default Summary Box

variants:
  - name: info
    label: Info
    context:
      summaryBox:
        classes: "usa-summary-box--info"
        title: Informative Summary Box

  - name: success
    label: Success
    context:
      summaryBox:
        classes: "usa-summary-box--success"
        title: Success Summary Box

  - name: warning
    label: Warning
    context:
      summaryBox:
        classes: "usa-summary-box--warning"
        title: Warning Summary Box

  - name: error
    label: Error
    context:
      summaryBox:
        classes: "usa-summary-box--error"
        title: Error Summary Box
        role: "alert"
