label: Banner

context:
  banner:
    text: "An official website of the United States government"
    action: "Here’s how you know"
  domain:
    tld: ".gov"
    heading: |
      Official websites use $TLD
    text: |
      A website ending in <strong>$TLD</strong> indicates it is an official U.S. government organization.
  https:
    heading: |
      Secure $TLD websites use HTTPS
    text: |
      A <strong>lock</strong> ($LOCK_IMG) or <strong>https://</strong> before the website name indicates information you get or provide is transmitted securely.
